apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phonebook
spec:
  destination:
    name: ''
    namespace: phonebook-api-ns
    server: https://kubernetes.default.svc
  source:
    path: helm_chart/phonebook
    repoURL: https://github.com/iam-parag/springboot-app.git
    targetRevision: CI-CD
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
