apiVersion: v1
kind: Service
metadata:
  name: {{ include "phonebook.fullname" . }}-service
  namespace: {{ template "phonebook.namespace" . }}
  labels:
    {{- include "phonebook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "phonebook.selectorLabels" . | nindent 4 }}
