---
apiVersion: v1
kind: Namespace
metadata:
  name: phonebook-api-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configmap
  namespace: phonebook-api-ns
data:
  DB_NAME: phonebook
  DB_USERNAME: phonebook
  DB_HOST: mysql-service
---
apiVersion: v1
kind: Secret
metadata:
  name: application-secret
  namespace: phonebook-api-ns
type: Opaque
data:
  DB_PASSWORD: cGhvbmVib29r
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: application
  name: application-deployment
  namespace: phonebook-api-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - application
      containers:
      - image: parag52/phonebook
        name: application
        ports:
        - containerPort: 8280
        envFrom:
          - configMapRef:
              name: application-configmap
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: application-secret
              key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
  namespace: phonebook-api-ns
spec:
  selector:
    app: application
  ports:
  - protocol: TCP
    port: 8280
    targetPort: 8280
    nodePort: 30007
  type: NodePort
