---
apiVersion: v1
kind: Namespace
metadata:
  name: phonebook-api-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  namespace: phonebook-api-ns
data:
  MYSQL_DATABASE: phonebook
  MYSQL_USER: phonebook
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: phonebook-api-ns
type: Opaque
data:
  MYSQL_PASSWORD: cGhvbmVib29r # Base64 encoded value of "mypassword"
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # Base64 encoded value of "rootpassword"
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql-deployment
  namespace: phonebook-api-ns
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:latest
        name: mysql
        ports:
        - containerPort: 3306
        envFrom:
          - configMapRef:
              name: mysql-configmap
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: phonebook-api-ns
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
