{{- if .Values.secretstore.create -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "secretstore.secretStoreName" . }}
  namespace: {{ template "secretstore.namespace" . }}
spec:
  provider:
    vault:
      server: {{.Values.secretstore.provider.vault.server}}
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: {{ include "secretstore.secretName" . }}
          key: "token"
{{- end }}