name: Phonebook-CI
on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
jobs:

  # hadolint:
  #   name: Run hadolint scanning for docker file
  #   needs: [lint]
  #   runs-on: self-hosted
  #   permissions:
  #     contents: read # for actions/checkout to fetch code
  #     security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
  #     actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Run hadolint
  #       uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
  #       with:
  #         dockerfile: ./Dockerfile
  #         format: sarif
  #         output-file: hadolint-results.sarif
  #         no-fail: true

  #     - name: Upload analysis results to GitHub
  #       uses: github/codeql-action/upload-sarif@v3
  #       with:
  #         sarif_file: hadolint-results.sarif
  #         wait-for-processing: true
  build:
    name: Docker Build and Push
    # needs: [hadolint]
    runs-on: self-hosted
    outputs:
      steps: ${{ steps.timestamp.outputs }}
    env:
      IMAGE_NAME: phonebook # Define the image name
    # strategy:
    #   matrix:
    #     environment: [dev, staging, production] # Define your environments
    steps:
    # Checkout the code
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set timestamp variable
      id: vars
      run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_ENV"
    

 
        
# Build and push multi-platform Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        #platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME}}:${{ env.TIMESTAMP }}
  
  update-values:
    name: Update values.yaml with latest image
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update values.yaml
        run: |
          sed -i 's|tag:.*|tag: ${{ env.TIMESTAMP }}|' helm_chart/phonebook/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add helm_chart/phonebook/values.yaml
          git commit -m 'Update values.yaml with latest image tag'
          git push
