name: Phonebook-CI
on:
  push:
    branches: [ CI-CD ]
  pull_request:
    branches: [ CI-CD ]
jobs:
  lint:
    name: Run lint scanning for Java code
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Workspace
        run: ls -R

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Checkstyle
        run: |
          curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.3/checkstyle-10.12.3-all.jar

      - name: Run Checkstyle
        run: |
          java -jar checkstyle.jar -c config/checkstyle.xml src/main/java/com/evertcode/phonebook/PhonebookApplication.java
      - name: Download PMD
        run: |
          curl -L -o pmd-bin.zip https://github.com/pmd/pmd/releases/download/pmd_releases/6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin.zip -d pmd-bin
      - name: Run PMD
        run: |
          ./pmd-bin/pmd-bin-6.55.0/bin/run.sh pmd -d src -R config/ruleset.xml -f text
      - name: Download SpotBugs
        run: |
          curl -L -o spotbugs-bin.zip https://github.com/spotbugs/spotbugs/releases/download/4.7.3/spotbugs-4.7.3.zip
          unzip spotbugs-bin.zip -d spotbugs-bin
          
      - name: Grant Execute Permissions to SpotBugs
        run: chmod +x ./spotbugs-bin/spotbugs-4.7.3/bin/spotbugs

      - name: Run SpotBugs
        run: |
          export SPOTBUGS_OPTS="-Xmx2g"
          ./spotbugs-bin/spotbugs-4.7.3/bin/spotbugs -textui -effort:max -low .
  hadolint:
    name: Run hadolint scanning for docker file
    runs-on: self-hosted
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
  build:
    name: Docker Build and Push
    needs: [lint, hadolint]
    runs-on: self-hosted
    env:
      IMAGE_NAME: phonebook # Define the image name
    # strategy:
    #   matrix:
    #     environment: [dev, staging, production] # Define your environments
    steps:
    # Checkout the code
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
# Build and push multi-platform Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        #platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME}}:latest
