name: Phonebook-CI
on:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'
jobs:
  build:
    name: Docker Build and Push
    needs: [hadolint]
    runs-on: self-hosted
    env:
      IMAGE_NAME: phonebook # Define the image name
    # strategy:
    #   matrix:
    #     environment: [dev, staging, production] # Define your environments
    steps:
    # Checkout the code
    - uses: actions/checkout@v4
    
    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set timestamp variable
      id: vars
      run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> "$GITHUB_ENV"
    

 
        
# Build and push multi-platform Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        #platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME}}:${{ env.TIMESTAMP }}
  
  update-values:
    name: Update values.yaml with latest image
    needs: [build]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update values.yaml
        run: |
          sed -i 's|tag:.*|tag: ${{ steps.vars.outputs.TIMESTAMP }}|' helm_chart/phonebook/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add helm_chart/phonebook/values.yaml
          git commit -m 'Update values.yaml with latest image tag'
          git push
