name: Phonebook-CI
on:
  push:
    branches: [ CI-CD ]
  pull_request:
    branches: [ CI-CD ]
jobs:
  lint:
    name: Run lint scanning for Java code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Workspace
        run: ls -R

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Checkstyle
        run: |
          curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.3/checkstyle-10.12.3-all.jar

      - name: Run Checkstyle
        run: |
          pwd 
          ls
          java -jar checkstyle.jar -c config/checkstyle.xml src/main/java/com/evertcode/phonebook/PhonebookApplication.java
      - name: Run PMD
        run: |
          ./pmd-bin/bin/run.sh pmd -d src -R ruleset.xml -f text
      - name: Run SpotBugs
        run: |
          ./spotbugs-bin/spotbugs src/
