name: Phonebook-CI
on:
  push:
    branches: [ CI-CD ]
  pull_request:
    branches: [ CI-CD ]
jobs:
  # lint:
  #   name: Run lint scanning for Java code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up JDK
  #       uses: actions/setup-java@v2
  #       with:
  #         distribution: 'temurin'
  #         java-version: '11'
  lintr:
    name: Run lintr scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@4e1feaf90520ec1215d1882fdddfe3411c08e492

      - name: Setup lintr
        uses: r-lib/actions/setup-r-dependencies@4e1feaf90520ec1215d1882fdddfe3411c08e492
        with:
          extra-packages: lintr

      - name: Run lintr
        run: lintr::sarif_output(lintr::lint_dir("."), "lintr-results.sarif")
        shell: Rscript {0}
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lintr-results.sarif
          wait-for-processing: true

      # - name: Install Checkstyle
      #   run: |
      #     curl -L -o checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.3/checkstyle-10.12.3-all.jar
      #     alias checkstyle='java -jar $(pwd)/checkstyle.jar'
      # - name: Find and Lint Java Files
      #   run: |
      #     pwd
      #     ls
      #     find src -name "*.java" > java_files.txt
      #     java -jar checkstyle.jar -c .checkstyle.xml $(cat java_files.txt)
      # - name: Run Checkstyle
      #   run: |
      #     java -jar checkstyle.jar -c .checkstyle.xml src/**/*.java
